version: "3"

services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./:/go/src/app
    ports:
      - 9119:8000
    depends_on:
      - db
      - redis
    links:
      - db
      - redis

  db:
    image: postgres:11.1-alpine
    restart: always
    environment:
      POSTGRES_DB: mep_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080

  redis:
    image: redis:4.0.14
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    entrypoint: redis-server --appendonly yes
    restart: always
